### ISSUE TITLE
login as guest user not working

### ISSUE THREAD

**Issue by famecrush** [anuraagnagar/flask-user-authentication#1]
These repo is very fine but the only these is that the login as guest user functionality not working
when i try to login as a genuine user by providing its credentials which i have registered before it will get logged in and show the home page but for guest user it doesn't redirect me.When I try to login as guest user it will execute these following code from file ' __init__ .py'.
"
@app.errorhandler(400)
    def bad_request(e):
        flash("Something went wrong.", 'error')
        return redirect(url_for('accounts.index')
"

**Comment by anuraagnagar** [comment]
Yes! Because the IaaS service I use, '**Python Anywhere**', is currently running this repo in the free tier, and they do not want to use third-party services like sending emails. To activate user accounts, an email was sent to the user's email address, and they confirm and log in afterward. 
**For guest users**, I already created profiles when setting up this repo. I restrict some endpoints to prevent users from updating their guest user profiles, as they often input unnecessary text into fields that only users can read.
